### PR TITLE
Add ToggleComments keymap

### PR DESCRIPTION
**Pull request by oliverpool**
From https://docs.helix-editor.com/keymap.html (look for `toggle_comments`).

I hope that I put them in the right place (normal + space mode).

### CODE REVIEW

**Comment by noahfraiture** [comment]
This way you added "space c" for every mode and "ctrl c" only in normal mode. But in helix "ctrl c" like "space c" works both in normal and selection mode

**Comment by oliverpool** [comment]
In the documentation the `crtl-c` was under `normal mode`, hence my (conservative) choice. I updated it to make it available in all modes!

**Comment by noahfraiture** [comment]
Great thank you for your PR !

**Comment by oliverpool** [comment]
thank you for starting this work !

**Pull request merged**
